export enum FeatureFlags {
  insightsRecommendations = 'insightsRecommendations',
  cloudSso = 'cloudSso',
  cloudSsoRecommendedSettings = 'cloudSsoRecommendedSettings',
  databaseChat = 'databaseChat',
  documentationChat = 'documentationChat',
  envDependent = 'envDependent',
  rdi = 'redisDataIntegration',
  hashFieldExpiration = 'hashFieldExpiration',
  enhancedCloudUI = 'enhancedCloudUI',
  cloudAds = 'cloudAds',
  databaseManagement = 'databaseManagement',
  customTutorials = 'customTutorials',
  vectorSearchV2 = 'vectorSearchV2',
  vectorSet = 'vectorSet',
  array = 'array',
  azureEntraId = 'azureEntraId',
  devBrowser = 'dev-browser',
  devLanguage = 'dev-language',
  whatsNew = 'whatsNew',
  valueDecoder = 'valueDecoder',
}
