name: Tests BE
on:
  workflow_call:
    inputs:
      skip-electron-deps:
        description: Skip install electron dependencies
        type: boolean
        default: false
        required: false

env:
  REPORT_NAME: 'report-be'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - name: Install all libs and dependencies for BE
        uses: ./.github/actions/install-all-build-libs
        with:
          skip-system-deps: '1'

      - name: Unit tests API
        timeout-minutes: 20
        run: npm run test:cov --prefix redisinsight/api -- --ci --silent

      - name: Upload Test Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: ${{ env.REPORT_NAME }}
          path: redisinsight/api/report
