name: ✅ E2E Tests

on:
  push:
    branches:
      - 'e2e/**'

permissions:
  actions: read
  contents: read
  checks: write
  pull-requests: write

jobs:
#  build-docker:
#    uses: ./.github/workflows/pipeline-build-docker.yml
#    secrets: inherit
#    with:
#      debug: ${{ inputs.debug || false }}
#      for_e2e_tests: true

  e2e-docker-tests-smoke:
    name: "E2E: Smoke (Docker)"
#    needs: build-docker
    uses: ./.github/workflows/tests-e2e-docker-smoke.yml
    secrets: inherit
    with:
      debug: ${{ inputs.debug || false }}

  e2e-docker-tests-critical-path:
    name: "E2E: Critical Path (Docker)"
#    needs: build-docker
    uses: ./.github/workflows/tests-e2e-docker-critical-path.yml
    secrets: inherit
    with:
      debug: ${{ inputs.debug || false }}

  e2e-docker-tests-regression:
    name: "E2E: Regression (Docker)"
    #    needs: build-docker
    uses: ./.github/workflows/tests-e2e-docker-regression.yml
    secrets: inherit
    with:
      debug: ${{ inputs.debug || false }}

  # Remove artifacts from github actions
  remove-artifacts:
    name: Remove artifacts
    needs:
      [
        e2e-docker-tests-smoke,
        e2e-docker-tests-critical-path,
        e2e-docker-tests-regression,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove all artifacts
        uses: ./.github/actions/remove-artifacts
