name: ✅ E2E Tests

on:
  push:
    branches:
      - 'e2e/**'

permissions:
  actions: read
  contents: read

jobs:
  build-docker:
    uses: ./.github/workflows/pipeline-build-docker.yml
    secrets: inherit
    with:
      debug: ${{ inputs.debug || false }}
      for_e2e_tests: true

  e2e-docker-tests:
    needs: build-docker
    uses: ./.github/workflows/tests-e2e-docker-debug.yml
    secrets: inherit
    with:
      debug: ${{ inputs.debug || false }}
